[tools]
rojo = "rojo-rbx/rojo@7.3.0"
selene = "Kampfkarren/selene@0.26.1"
wally = "UpliftGames/wally@0.3.2"
stylua = "JohnnyMorganz/stylua@0.19.1"
remodel = "rojo-rbx/remodel@0.11.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.2.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.27.0"
