[package]
name = "nbala/sheriff-showdown"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.packages"

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Component = "sleitnick/component@2.4.8"
Promise = "evaera/promise@4.0.0"
React = "jsdotlua/react@17.2.0"
ReactRoblox = "jsdotlua/react-roblox@17.2.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
Janitor = "howmanysmall/janitor@1.17.0"
Input = "sleitnick/input@2.3.0"
Sift = "csqrl/sift@0.0.9"
Freeze = "duckarmor/freeze@0.1.4"
Timer = "sleitnick/timer@1.1.2"
Symbol = "core-packages/symbol@1.1.0"
t = "osyrisrblx/t@3.1.1"
Net = "vorlias/net@3.0.7"
Comm = "sleitnick/comm@1.0.1"
Matter = "matter-ecs/matter@0.8.4"
MatterReplication = "vocksel/matter-replication@0.1.1"
MatterHooks = "matter-ecs/matter-hooks@0.2.1"
Spark = "nezuo/spark@0.2.1"
Plasma = "matter-ecs/plasma@0.4.4"

[server-dependencies]
Cmdr = "evaera/cmdr@1.12.0"
Lapis = "nezuo/lapis@0.3.3"